########################################
# CONSTANTS
########################################
uint8 EYE    = 0
uint8 NOISE  = 1
uint8 MOUTH  = 2
uint8 EAR    = 3
uint8 NICK   = 4
uint8 HAND   = 5
uint8 FOOT   = 6

uint8 NORMAL =0
uint8 HIGH   =1

########################################
# Messages
########################################
uint8 status
uint8 cmd_by 
uint8 cmd_type
string msg
uint8 priority
